# Generated by Django 5.1.5 on 2025-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0030_alter_photo_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exif_lens_model',
            field=models.CharField(blank=True, help_text="eg, 'E PZ 16-50mm F3.5-5.6 OSS'.", max_length=100),
        ),
    ]
