# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 14:56
from __future__ import unicode_literals

import ditto.flickr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flickr", "0014_photo_original_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="original_file",
            field=models.FileField(
                blank=True, default="", upload_to=ditto.flickr.models.Photo.upload_path
            ),
        ),
    ]
