# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scrobble',
            options={'ordering': ['-post_time']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name']},
        ),
    ]
